### ISSUE TITLE
Accès au profil et aux bordereaux

### ISSUE THREAD

**Issue by jframiara** [PPEFrediLimayrac/Fredy#5]
La page bordereau.php n'est accessible que depuis la page apresconnexion.php. Elle n'est pas dans le menu de l'appli...
C'est pourtant la seule qui permet d'accéder au profil ou aux bordereaux

**Comment by Clementjosephlimayrac** [comment]
Si elle l'est. Il suffit de cliquer sur " connecté en tant que *****". 

Il s'agit en fait d'un bouton (il devient orange lorsque l'on le survole avec la souris).

http://prntscr.com/iuu6da  <= photo explicative !
