### ISSUE TITLE
Affichage de la rue dans le formulaire du licencié

### ISSUE THREAD

**Issue by jframiara** [PPEFrediLimayrac/Fredy#6]
Quand on modifie un licencié et que la rue contient "des roses", le formulaire affiche "des" seulement.

**Comment by Clementjosephlimayrac** [comment]
Problème non trouvé sur la version actuelle. Pouvez vous retester sur la nouvelle version et me dire si le bug persiste ? Merci

**Comment by AdrienAlaryLim** [comment]
Après quelques tests, le problème a été trouvé puis résolu. La lecture du php ne s'effectuait pas correctement dans le formulaire.
