### ISSUE TITLE
Erreur lors de la création d'un borderau

### ISSUE THREAD

**Issue by jframiara** [PPEFrediLimayrac/Fredy#7]
Quand on veut créer un bordereau, on obtient cette erreur : 

> Uncaught exception 'Exception' with message 'Erreur lors de la requête SQL : SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db_fredi`.`avancer`, CONSTRAINT `FK_avancer_id_notedefrais` FOREIGN KEY (`id_notedefrais`) REFERENCES `notedefrais` (`id_notedefrais`))' in C:\xampp\htdocs\projets\PPE3\plot1\includes\LigneFraisDAO.php on line 137

**Comment by Clementjosephlimayrac** [comment]
L'erreur est normalement corrigée.
