### ISSUE TITLE
Erreur lors de la déconnexion

### ISSUE THREAD

**Issue by jframiara** [PPEFrediLimayrac/Fredy#8]
Lorsque l'on veut se déconnecter, on obtient cette erreur : 

> Objet non trouvé! L'URL demandée n'a pas pu être trouvée sur ce serveur.

L'URL recherchée est : http://localhost/projets/PPE3/plot1/includes/deconnexion.php

**Comment by Clementjosephlimayrac** [comment]
Problème normalement corrigé, me signaler si elle persiste.

**Comment by AdrienAlaryLim** [comment]
Avec la mise en place du système de recherche de 'BASEURL', relative aux éléments du menu, l'erreur ne doit effectivement plus se produire.
